package com.iapppay.consumer.dto.dimdto;

import java.util.Date;

/**
 * 
 * @className: DimPaychanRef
 * @classDescription:产品大类对象
 * @author lishiqiang
 * @create_date: 2019年5月7日 上午11:28:03
 * @update_date:
 */
public class DimPaychanRef {
    private Integer id;

    private Double paychannel;

    private String paychannelname;

    private Double channelaccountid;

    private String channelaccountname;

    private String merchantno;

    private Double paytype;

    private String paytypename;

    private Double opchanno;

    private String opchanname;

    private Double channo;

    private Double ckchanno;

    private Double spchanno;

    private String spchanname;

    private String channamealias;

    private Double spchannotype;

    private Float spchannorate;

    private Double spchannolowerfee;

    private String rateextrule;

    private Double settleflag;

	private Double settlechannelid;

	private String settlechannelname;

	private Integer settlechanneltype;

    private Boolean isinvoice;

	private Integer spability;

    private Boolean isroyalty;

    private Double buschanrate;

    private Date inserttime;

    private Date updatetime;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.id
     *
     * @param id the value for dim_paychan_ref.id
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.paychannel
     *
     * @return the value of dim_paychan_ref.paychannel
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getPaychannel() {
        return paychannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.paychannel
     *
     * @param paychannel the value for dim_paychan_ref.paychannel
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setPaychannel(Double paychannel) {
        this.paychannel = paychannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.paychannelname
     *
     * @return the value of dim_paychan_ref.paychannelname
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public String getPaychannelname() {
        return paychannelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.paychannelname
     *
     * @param paychannelname the value for dim_paychan_ref.paychannelname
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setPaychannelname(String paychannelname) {
        this.paychannelname = paychannelname == null ? null : paychannelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.channelaccountid
     *
     * @return the value of dim_paychan_ref.channelaccountid
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getChannelaccountid() {
        return channelaccountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.channelaccountid
     *
     * @param channelaccountid the value for dim_paychan_ref.channelaccountid
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setChannelaccountid(Double channelaccountid) {
        this.channelaccountid = channelaccountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.channelaccountname
     *
     * @return the value of dim_paychan_ref.channelaccountname
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public String getChannelaccountname() {
        return channelaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.channelaccountname
     *
     * @param channelaccountname the value for dim_paychan_ref.channelaccountname
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setChannelaccountname(String channelaccountname) {
        this.channelaccountname = channelaccountname == null ? null : channelaccountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.merchantno
     *
     * @return the value of dim_paychan_ref.merchantno
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public String getMerchantno() {
        return merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.merchantno
     *
     * @param merchantno the value for dim_paychan_ref.merchantno
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setMerchantno(String merchantno) {
        this.merchantno = merchantno == null ? null : merchantno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.paytype
     *
     * @return the value of dim_paychan_ref.paytype
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.paytype
     *
     * @param paytype the value for dim_paychan_ref.paytype
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setPaytype(Double paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.paytypename
     *
     * @return the value of dim_paychan_ref.paytypename
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public String getPaytypename() {
        return paytypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.paytypename
     *
     * @param paytypename the value for dim_paychan_ref.paytypename
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setPaytypename(String paytypename) {
        this.paytypename = paytypename == null ? null : paytypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.opchanno
     *
     * @return the value of dim_paychan_ref.opchanno
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getOpchanno() {
        return opchanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.opchanno
     *
     * @param opchanno the value for dim_paychan_ref.opchanno
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setOpchanno(Double opchanno) {
        this.opchanno = opchanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.opchanname
     *
     * @return the value of dim_paychan_ref.opchanname
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public String getOpchanname() {
        return opchanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.opchanname
     *
     * @param opchanname the value for dim_paychan_ref.opchanname
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setOpchanname(String opchanname) {
        this.opchanname = opchanname == null ? null : opchanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.channo
     *
     * @return the value of dim_paychan_ref.channo
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getChanno() {
        return channo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.channo
     *
     * @param channo the value for dim_paychan_ref.channo
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setChanno(Double channo) {
        this.channo = channo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.ckchanno
     *
     * @return the value of dim_paychan_ref.ckchanno
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getCkchanno() {
        return ckchanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.ckchanno
     *
     * @param ckchanno the value for dim_paychan_ref.ckchanno
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setCkchanno(Double ckchanno) {
        this.ckchanno = ckchanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.spchanno
     *
     * @return the value of dim_paychan_ref.spchanno
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getSpchanno() {
        return spchanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.spchanno
     *
     * @param spchanno the value for dim_paychan_ref.spchanno
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setSpchanno(Double spchanno) {
        this.spchanno = spchanno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.spchanname
     *
     * @return the value of dim_paychan_ref.spchanname
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public String getSpchanname() {
        return spchanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.spchanname
     *
     * @param spchanname the value for dim_paychan_ref.spchanname
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setSpchanname(String spchanname) {
        this.spchanname = spchanname == null ? null : spchanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.channamealias
     *
     * @return the value of dim_paychan_ref.channamealias
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public String getChannamealias() {
        return channamealias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.channamealias
     *
     * @param channamealias the value for dim_paychan_ref.channamealias
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setChannamealias(String channamealias) {
        this.channamealias = channamealias == null ? null : channamealias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.spchannotype
     *
     * @return the value of dim_paychan_ref.spchannotype
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getSpchannotype() {
        return spchannotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.spchannotype
     *
     * @param spchannotype the value for dim_paychan_ref.spchannotype
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setSpchannotype(Double spchannotype) {
        this.spchannotype = spchannotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.spchannorate
     *
     * @return the value of dim_paychan_ref.spchannorate
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Float getSpchannorate() {
        return spchannorate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.spchannorate
     *
     * @param spchannorate the value for dim_paychan_ref.spchannorate
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setSpchannorate(Float spchannorate) {
        this.spchannorate = spchannorate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.spchannolowerfee
     *
     * @return the value of dim_paychan_ref.spchannolowerfee
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getSpchannolowerfee() {
        return spchannolowerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.spchannolowerfee
     *
     * @param spchannolowerfee the value for dim_paychan_ref.spchannolowerfee
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setSpchannolowerfee(Double spchannolowerfee) {
        this.spchannolowerfee = spchannolowerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.rateextrule
     *
     * @return the value of dim_paychan_ref.rateextrule
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public String getRateextrule() {
        return rateextrule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.rateextrule
     *
     * @param rateextrule the value for dim_paychan_ref.rateextrule
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setRateextrule(String rateextrule) {
        this.rateextrule = rateextrule == null ? null : rateextrule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.settleflag
     *
     * @return the value of dim_paychan_ref.settleflag
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getSettleflag() {
        return settleflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.settleflag
     *
     * @param settleflag the value for dim_paychan_ref.settleflag
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setSettleflag(Double settleflag) {
        this.settleflag = settleflag;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.isinvoice
     *
     * @return the value of dim_paychan_ref.isinvoice
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Boolean getIsinvoice() {
        return isinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.isinvoice
     *
     * @param isinvoice the value for dim_paychan_ref.isinvoice
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setIsinvoice(Boolean isinvoice) {
        this.isinvoice = isinvoice;
    }


	public Double getSettlechannelid() {
		return settlechannelid;
	}

	public void setSettlechannelid(Double settlechannelid) {
		this.settlechannelid = settlechannelid;
	}

	public String getSettlechannelname() {
		return settlechannelname;
	}

	public void setSettlechannelname(String settlechannelname) {
		this.settlechannelname = settlechannelname;
	}

	public Integer getSettlechanneltype() {
		return settlechanneltype;
	}

	public void setSettlechanneltype(Integer settlechanneltype) {
		this.settlechanneltype = settlechanneltype;
	}

	public Integer getSpability() {
		return spability;
	}

	public void setSpability(Integer spability) {
		this.spability = spability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column dim_paychan_ref.isroyalty
	 *
	 * @return the value of dim_paychan_ref.isroyalty
	 *
	 * @mbg.generated Tue May 07 11:20:21 CST 2019
	 */
    public Boolean getIsroyalty() {
        return isroyalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.isroyalty
     *
     * @param isroyalty the value for dim_paychan_ref.isroyalty
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setIsroyalty(Boolean isroyalty) {
        this.isroyalty = isroyalty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.buschanrate
     *
     * @return the value of dim_paychan_ref.buschanrate
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Double getBuschanrate() {
        return buschanrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.buschanrate
     *
     * @param buschanrate the value for dim_paychan_ref.buschanrate
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setBuschanrate(Double buschanrate) {
        this.buschanrate = buschanrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.inserttime
     *
     * @return the value of dim_paychan_ref.inserttime
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Date getInserttime() {
        return inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.inserttime
     *
     * @param inserttime the value for dim_paychan_ref.inserttime
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setInserttime(Date inserttime) {
        this.inserttime = inserttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_paychan_ref.updatetime
     *
     * @return the value of dim_paychan_ref.updatetime
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_paychan_ref.updatetime
     *
     * @param updatetime the value for dim_paychan_ref.updatetime
     *
     * @mbg.generated Tue May 07 11:20:21 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}